# Generated by Django 3.2.19 on 2023-10-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_reviews_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='rating',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
